name: Actions in action

on:
  - push

jobs:
  gh-action:
    runs-on: ubuntu-latest
    steps:
      - 
        name: list files
        run: |
          pwd
          ls -halp

      - 
        name: checkout
        uses: actions/checkout@v1

      - 
        name: list files again
        run: |
          pwd
          ls -halp

      - 
        id: greet
        name: smpl-js-act
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John

      - 
        name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
