name: Great escape

on:
  - push

jobs:
  hide-n-seek:
    runs-on: ubuntu-latest
    container: curlimages/curl:latest
    steps:
      - 
        name: access the internet
        run: curl "https://postman-echo.com/get"
